export const I18N = {
    locales: [ 
      {code:'en',name: "English"},
      {code:'fr',name: "Français"},
      {code:'ja',name: "日本語"},
      {code:'it',name: "Italiano"},
      {code:'es',name: "Español"},
      {code:'de',name: "Deutsch"},
      {code:'ar',name: "العربية"},
      {code:'ca',name: "Català"},
      {code:'el',name: "Greek"},
      {code:'hi',name: " हिन्दी"},
      {code:'id',name: "Bahasa Indonesia"},
      {code:'ko',name: "한국어"},
      {code:'ms',name: "Bahasa Melayu"},
      {code:'nl',name: "Nederlands"},
      {code:'pl',name: "Polski"},
      {code:'pt',name: " Português"},
      {code:'ru',name: "Pусский"},
      {code:'sv',name: "Svenska"},
      {code:'th',name: " ภาษาไทย"},
      {code:'tr',name: "Türkçe"},
      {code:'uk',name: "Українська"},
      {code:'vi',name: "Tiếng Việt"},
    { code: 'zh_c', name_c: "中文(简体)" },
    { code: 'zh_t', name_t: "中文(繁體)" },
      {code:'bg',name: "Български"},
    ],
    defaultLocale: 'en',
    vueI18n: {
      fallbackLocale: 'en',
      messages: {
        ar: require('../locales/ar.json'),
        bg: require('../locales/bg.json'), 
        ca: require('../locales/ca.json'), 
        de: require('../locales/de.json'), 
        el: require('../locales/el.json'), 
        en: require('../locales/en.json'), 
        es: require('../locales/es.json'), 
        fr: require('../locales/fr.json'), 
        hi: require('../locales/hi.json'), 
        id: require('../locales/id.json'), 
        it: require('../locales/it.json'), 
        ja: require('../locales/ja.json'), 
        ko: require('../locales/ko.json'), 
        ms: require('../locales/ms.json'), 
        nl: require('../locales/nl.json'), 
        pl: require('../locales/pl.json'), 
        pt: require('../locales/pt.json'), 
        ru: require('../locales/ru.json'), 
        sv: require('../locales/sv.json'), 
        th: require('../locales/th.json'), 
        tr: require('../locales/tr.json'), 
        uk: require('../locales/uk.json'), 
        vi: require('../locales/vi.json'), 
        zh_c: require('../locales/zh_c.json'), 
        zh_t: require('../locales/zh_t.json')
      },
    }, 
  };
  